#!/usr/bin/env bash
# bash script that display information about subdomains

world_wide_web ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", sd, $4, $5}' sd="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ];
    then
        world_wide_web "$1" "$subdomain"
    fi
done