#!/usr/bin/env bash
#redirecting to another page.
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_string="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed-i "s|server_name\ _;|$new_string|" /etc/nginx/sites-available/default
sudo service nginx rstart
