#!/usr/bin/env bash
#redirecting to another page.
new_string="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed-i "s@server_name _;@{$new_string}" /etc/nginx/sites-available/default
sudo service nginx start
