#!/usr/bin/env bash                                                                                                                                           
#Nginx should listen to port 80(automatition).                                                                                                                
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default                                                                                    
sudo service nginx restart