#!/usr/bin/env bash
# writing a bash script that displays To infinity and beyond with a sleep 2
# and when receiving a SIGTERM signal dispalys I am invincible!!!
trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
