#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ $i -le 10 ]
do
	echo "Best School"
        if [ $i = 4 ]
        then
                echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	fi
	i=$((i = i + 1))
done
