#!/usr/bin/env bash
#Bash script that configures the container to fit the above requirements
pkill -f apache2
chmod 700 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo su nginx service nginx start